---
# playbook.yml
- hosts: all
  become: yes
  vars:
    username: "packer"
    password: "P@ck3r"
  tasks:
    - name: Install Packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - nano

    - name: Ensuring that wheel is able to use sudo without password
      lineinfile:
        path: /etc/sudoers
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Set includedir in sudoers
      lineinfile:
        dest: /etc/sudo.conf
        line: "#includedir /etc/sudoers.d"
        state: present
        validate: "/usr/sbin/visudo -cf %s"

    - name: Add users to sudo
      lineinfile:
        path: "/etc/sudoers.d/{{ username }}"
        line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
        state: present
        mode: 0440
        create: yes
        validate: 'visudo -cf %s'

    - name: Set timezone.
      timezone:
        name: "America/Los_Angeles"
